### ISSUE TITLE
Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by orimdominic** [ctrlplusb/zeit-now-node-server#8]
I keep getting the error
```bash
Cannot set headers after they are sent to the clientError [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

      at send (node_modules/micro/lib/index.js:76:6)
      at sendError (node_modules/micro/lib/index.js:83:2)
      at node_modules/micro/lib/index.js:110:17
```
I'm testing with Jest and my serverless function (which works in production) is something like this (I whittled it down to what you are seeing in the code and I still got the error)
```javascript
import { VercelRequest, VercelResponse } from "@vercel/node";

module.exports = async (req: VercelRequest, res: VercelResponse) => {
  res.status(200).send("hello")
}
```
Here is how my test file looks
```javascript
import * as request from "request";
import { createServer } from "vercel-node-server";
import listen from "test-listen";
import { promisify } from "util";
const lambdaFn = require("./path-to-lamda-fn");

const get = promisify(request.get);
let server: any;
let url: string;

describe("name of test", () => {
  // beforeAll(async () => {
  //     server = createServer(twitterWebhookLambda);
  //     url = await listen(server)
  //     console.log("url:", url);
  // });

  // afterAll(() => {
  //   server.close();
  // });

  it("should return the expected response", async () => {
    const server = createServer(lambdaFn)
    server.listen(8000)
    const res = await get({url: "http://localhost:8000"})
    expect (res.statusCode).toBe(200)
    server.close()
  });
});

```
OS: Ubuntu 20
Node version: 14.x
Yarn version: 1.22.x
"vercel": "^22.0.1"

I also tried it with Axios and I got the same error

Nice work here!

**Comment by sudo-kaizen** [comment]
I also tried it with Axios and I got the same error

**Comment by Tchoupinax** [comment]
Hello @sudo-kaizen,

I got the same error. I successfully make my test passing with rewriting the code from 'res.send()` to simple `return`. However, removing `res.send()` prevent Vercel from correctly working.

I do not know why this package does not respect the Vercel's behaviour... Maybe we could fix it ^^

Have a nice day!

**Comment by orimdominic** [comment]
@Tchoupinax Nice. I think this project is not under active maintenance anymore. Sad.
I ended up using [node-mocks-http](https://www.npmjs.com/package/node-mocks-http) for this
Cheers!

**Comment by Tchoupinax** [comment]
@sudo-kaizen Thanks :)
For your information, there is the [nock](https://github.com/nock/nock) project that allows to mock any http request in your test.
Cheers :)
